client_config_backend: file
client_config:
    client_id: 18382680566-6r1l0an18fivsrt6lbcmhtcj25l3u1j7.apps.googleusercontent.com
    client_secret: klsXlhTvWJnnAVtUofOPDQqP

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
    - https://www.googleapis.com/auth/drive
    - https://www.googleapis.com/auth/drive.install